%% 数据结构定义
%
% by Dr. Guan Guoqiang @ SCUT on 2020-06-24

% 定义成绩单的数据结构
Def_EvalWays = struct('Description', 'X大题XX小题', ...
                      'Code', 'A1', ...
                      'Weight', 0.05, ...
                      'FullCredit', 2);
Def_EvalTypes = struct('Description', '期末考试', ...
                       'Code', 'A', ...
                       'Weight', 0.7, ...
                       'EvalWays', struct);
Def_Definition = struct('Spec', [5 4 1], ...
                        'EvalTypes', struct);
Def_Transcript = struct('Definition', struct, ...
                        'Detail', table);